### ISSUE TITLE
[Bug]: error when run pnpm storybook command

### ISSUE THREAD

**Issue by accentureJoabeChaves** [jhanke00/next-product-site#73]
### Contact Details

joabe.f.chaves@accenture.com

### What happened?

Receive an error when run command 
```bash
pnpm storybook
```
environment:
- Linux Ubuntu@22.04.3 (WSL)

### Relevant log output

```shell
ERROR in ./app/products/page.tsx 7:0-55
Module not found: Error: Can't resolve '@/src/mock/large/products.json' in '/home/joabe/developments/next-product-site/app/products'
 @ ./app/products/products.stories.tsx 4:0-30 7:13-21
 @ ././ lazy ^\.\/.*$ include: (?:(?:^%7C\/%7C(?:(?:(?%21(?:^%7C\/)\.).)*?)\/)(?%21\.)(?=.)[^/]*?\.stories\.(js%7Cjsx%7Cmjs%7Cts%7Ctsx))$ chunkName: [request] namespace object ./app/products/products.stories.tsx ./app/products/products.stories
 @ ./storybook-stories.js 23:11-27:5
 @ ./storybook-config-entry.js 6:0-50 25:21-29 28:2-31:4 28:58-31:3 30:31-39

ERROR in ./app/products/page.tsx 8:0-55
Module not found: Error: Can't resolve '@/src/mock/small/products.json' in '/home/joabe/developments/next-product-site/app/products'
 @ ./app/products/products.stories.tsx 4:0-30 7:13-21
 @ ././ lazy ^\.\/.*$ include: (?:(?:^%7C\/%7C(?:(?:(?%21(?:^%7C\/)\.).)*?)\/)(?%21\.)(?=.)[^/]*?\.stories\.(js%7Cjsx%7Cmjs%7Cts%7Ctsx))$ chunkName: [request] namespace object ./app/products/products.stories.tsx ./app/products/products.stories
 @ ./storybook-stories.js 23:11-27:5
 @ ./storybook-config-entry.js 6:0-50 25:21-29 28:2-31:4 28:58-31:3 30:31-39

preview compiled with 2 errors
=> Failed to build the preview
99% end closing watch compilationWARN Force closed preview build
SB_BUILDER-WEBPACK5_0003 (WebpackCompilationError): There were problems when compiling your code with Webpack.
Run Storybook with --debug-webpack for more information.
    at starter (./node_modules/.pnpm/@storybook+builder-webpack5@7.6.15_esbuild@0.18.20_typescript@5.3.3/node_modules/@storybook/builder-webpack5/dist/index.js:1:9660)
    at starter.next (<anonymous>)
    at Module.start (./node_modules/.pnpm/@storybook+builder-webpack5@7.6.15_esbuild@0.18.20_typescript@5.3.3/node_modules/@storybook/builder-webpack5/dist/index.js:1:11692)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by MichalJalowik** [comment]
I have resolved this issue locally. Would like to create PR but not have permission to create new branch.
